---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-loki-secret
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: garage-loki-secret
    creationPolicy: Owner
  data:
    - secretKey: access_key_id
      remoteRef:
        key: garage-loki-credentials
        property: access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: garage-loki-credentials
        property: secret_access_key
