---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: garage-loki-secret
      valuesKey: access_key_id
      targetPath: loki.storage.s3.access_key_id
    - kind: Secret
      name: garage-loki-secret
      valuesKey: secret_access_key
      targetPath: loki.storage.s3.secret_access_key
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      limits_config:
        retention_period: 720h
      storage:
        type: s3
        s3:
          endpoint: http://192.168.40.53:3900
          bucketnames: loki-chunks
          region: garage
          s3ForcePathStyle: true
    singleBinary:
      replicas: 1
      resources:
        requests:
          memory: 1Gi
          cpu: 250m
        limits:
          memory: 2Gi
