---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 04f31324-e66c-4f25-98cc-2d3548d8ba2c 
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
      - hostname: "*.daltonbuilds.com"
        service: https://cilium-gateway-homelab-gateway.gateway.svc.cluster.local
        originRequest:
          noTLSVerify: true
      - service: http_status:404
